
services: 
  uber:
    build:
      context: .
      dockerfile: ./apps/uber/Dockerfile
      cache_from:
        - node:20-alpine
  
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost/api
    networks:
      - app_network
    restart: unless-stopped

  uber-auth:
    build:
      context: .
      dockerfile: ./apps/uber-auth/Dockerfile
      cache_from:
        - node:20-alpine
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOSTNAME=0.0.0.0
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost/api
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge